name: objectbox_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  intl: any
  path_provider: ^2.0.10
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  objectbox_generator: any

flutter:
  uses-material-design: true
